name: Close linked issues when PR merged into release

on:
  pull_request:
    types: [closed]
    branches:
      - release
      - release7x

permissions:
  issues: write

jobs:
  closeIssueOnPrMerge:
    runs-on: ubuntu-latest
    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@643fb191160db90fbffd00bf1e4b608734628718
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
