name: Deploy

on: 
  workflow_dispatch:
    inputs:
      buildTimestamp:
        description: 'Build timestamp (empty to deploy the latest)'     
        required: true
        default: 'latest'

# if: github.ref == 'refs/heads/master'
# if: github.actor == 'lpoulter' || github.actor == 'kingthorin' or if: contains('["kingthorin","lpoulter"]', github.actor)

jobs:
  deploy:
    name: Deploy my app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://bytelegend.com
          environment: production
      - uses: actions/github-script@v4
        id: determine-latest
        with:
          script: |
            const page = await github.actions.listWorkflowRuns({
              owner: "blindpirate",
              repo: "test",
              workflow_id: "deploy.yml",
              per_page: 1,
            });
            console.log(JSON.stringify(page.data.workflow_runs[0]));
            return page.data.workflow_runs[0];
      - name: Show timestamp
        run: echo "${{ steps.determine-latest.outputs.result }}"
      - name: Deploy my app
        run: |
          echo "{{ github.event.inputs.buildTimestamp }}"
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://bytelegend.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://bytelegend.com
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
